db:
    image: ./docker-database-config
    ports:
        - "5432:5432"
web:
    build: .
    # command: python server.py
    ports:
        - "5000:5000"
    volumes:
        - .:/code
    links:
        - db
# mongo:
#     image: mongo
#     ports:
#         - "27017:27017"
