db:
    build: ./docker-database-config/
    ports:
        - "5432:5432"
web:
    build: .
    command: python datalayer/manage.py runserver 0.0.0.0:8000
    ports:
        - "8000:8000"
    volumes:
        - .:/datalayer
    links:
        - db
# mongo:
#     image: mongo
#     ports:
#         - "27017:27017"
